name: Create DevArt.API NuGet package

on:
  workflow_dispatch:

jobs:
  publish_nuget_package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          dotnet tool restore
          dotnet restore Utilities/DevArt.API.csproj

      - name: Pack
        run: dotnet pack Utilities/DevArt.API.csproj.csproj --no-restore -c Release

      - name: Push
        run: dotnet nuget push Utilities/DevArt.API.${env:NBGV_NuGetPackageVersion}.nupkg -s "github" -k ${{ secrets.GITHUB_TOKEN }}